[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pathapy"
version = "0.0.1"
authors = [
  { name="Lucas Diedrich", email="lucas.diedrich@embl.de" },
]
description = "A python package to create input files for ipath3"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
